id: A1B8D3BB6
title: Prayer for the Long Life of Pema Norbu, Lord of Siddhas
type: translation
pechas:
- I2C788F29
- I9534EB22
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:49:51.239158
  last_modified_at: 2023-01-04 12:49:51.239178
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I2C788F29/D58D: DA94
  I9534EB22/DC7D: DA94
